[package]
name = "watch-run"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
colored = "3.0.0"
globset = "0.4.18"
notify = "8.2.0"
notify-debouncer-mini = "0.7.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
